import type { Metadata } from "next";
import { Baloo_Bhaijaan_2, Poppins, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Card, CardContent } from "@/components/ui/card";
import { cn } from "@/lib/utils";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const balooBhaijaan = Baloo_Bhaijaan_2({
  subsets: ["latin"],
  variable: "--font-baloo-bhaijaan",
  weight: ["400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${balooBhaijaan.variable} ${poppins.variable} ${geistMono.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
